// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAeChvFAyhdsb4lUllc2e3NI4uuw4SOdVk",
    authDomain: "example-55514.firebaseapp.com",
    projectId: "example-55514",
    storageBucket: "example-55514.appspot.com",
    messagingSenderId: "853716179779",
    appId: "1:853716179779:web:e02f9e4a87e84056a3edf6",
    measurementId: "G-Z84NLKW7PN",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeChvFAyhdsb4lUllc2e3NI4uuw4SOdVk',
    appId: "1:853716179779:web:e02f9e4a87e84056a3edf6",
    messagingSenderId: '197024535596',
    projectId: "example-55514",
    storageBucket: "example-55514.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeChvFAyhdsb4lUllc2e3NI4uuw4SOdVk',
    appId: "1:853716179779:web:e02f9e4a87e84056a3edf6",
    messagingSenderId: '197024535596',
    projectId: "example-55514",
    storageBucket: "example-55514.appspot.com",
    iosClientId:
        '197024535596-1r3gg0emf0oocsq3bh1799l4ntcbsop5.apps.googleusercontent.com',
    iosBundleId: 'com.example.helper',
  );
}
