// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf36dKX-XfFGN49gDSdRCZNf3SGSAkhHk',
    appId: '1:197024535596:web:652f687ada199352f36d89',
    messagingSenderId: '197024535596',
    projectId: 'helpernew-fda96',
    authDomain: 'helpernew-fda96.firebaseapp.com',
    storageBucket: 'helpernew-fda96.appspot.com',
    measurementId: 'G-1T79K4TWLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3jhwvBxeAC5b1fqJ5BmvRgHv1iyAoU5k',
    appId: '1:197024535596:android:0e8102dde967c04df36d89',
    messagingSenderId: '197024535596',
    projectId: 'helpernew-fda96',
    storageBucket: 'helpernew-fda96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeeLiWqCP1g4BusjqC090tGHvoKlkCPo',
    appId: '1:197024535596:ios:65d222275380de35f36d89',
    messagingSenderId: '197024535596',
    projectId: 'helpernew-fda96',
    storageBucket: 'helpernew-fda96.appspot.com',
    iosClientId: '197024535596-1r3gg0emf0oocsq3bh1799l4ntcbsop5.apps.googleusercontent.com',
    iosBundleId: 'com.example.helper',
  );
}
